sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - downloads

matrix:
  include:
    - php: 7.1
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-stable --prefer-dist --no-interaction"
    - php: 7.3
      env:
        - COMPOSER_FLAGS="--prefer-dist --no-interaction"

before_script:
  - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit

notifications:
  slack:
    secure: "Gd3/1e0pBKvJv1UhWpBkWijJpmSWlarg6uPBJO0h4z1IpkZjd++jOjhmOQ7n+yMfuapQuJTcVOK0yIWu7orJoGAKFkBlMEIrLk1xMAG9phjjMLUO0FWgcQ3eVW5mTyfMBtClz4OL5wXckw17ohtXHDK8qnI0Hz9Qj8Rqgf2OZhM="
